### ISSUE TITLE
Local key extraction

### ISSUE THREAD

**Issue by GotierLdl** [velzend/create_ikohs_fan#15]
Hello,

I'm contacting you to find out how to retrieve the "local key". I've paired my fan with the "Create" app but I can't extract the local key.

Can you help me please ?

Thanks

**Comment by deese** [comment]
My proposal will be to use reset the pairing, pair it to the SmartLife app and follow the steps from https://github.com/jasonacox/tinytuya 

I have 3 windcalms DC and it works perfectly :D

**Comment by GotierLdl** [comment]
I recently corrected the problem.

**Comment by romainhe** [comment]
Hi @GotierLdl ! I have a Create fan too. Like you I've paired it to the Create App. (coupling only worked in "no-fail" mode)
How did you succeed in synchronizing it with Smart life..?
The procedures always ask for the device to be reset (on/off, on/off, on/off, etc.) but nothing seems to work as expected with the create model.

If you have a clue... 

Thx
