### ISSUE TITLE
Speed settings in Local Tuya

### ISSUE THREAD

**Issue by Schnabulation** [velzend/create_ikohs_fan#8]
I have the same fan and the local tuya integration works well.
However: I can't get the speed setting to work reliably. When I change the slider the fan beeps twice and then stops. What did you set for the DPS and Max / Min settings?

I used these settings:
![grafik](https://user-images.githubusercontent.com/1053834/179185631-0ce4ea2d-190b-4f68-b309-29a050f34390.png)
![grafik](https://user-images.githubusercontent.com/1053834/179185677-149a5bfa-071f-4f96-a10d-f6841bf55a44.png)

Also: Could you by any chance upload your custom card?

**Comment by 4nd0rn0t** [comment]
Hello, someone has reverse engineered the remote control (or has any information), working frequency, type of command to send, code is fixed or changing, if it has to be synchronized with the fan. It would be a good option to have a radio frequency to wifi or zigbee converter (I don't have the wifi model, and until the summer is over I can't mess around and investigate).

**Comment by nagubal** [comment]
@Schnabulation see the following comment by deese : https://github.com/rospogrigio/localtuya/issues/763#issuecomment-1139492051
This fan needs integers for the speed setting and localtuya sends it as a string.

I installed this fan yesterday and it works great after applying the modifications (but it will break the next time I upgrade the localtuya integration).

**Comment by Schnabulation** [comment]
@nagubal Oh this is awesome - thank you very much!

I have added another question on the other thread - if you also have an idea for this, that would be awesome.
